/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyect_1_estructura_de_datos;

import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jordi
 */
public class Principal extends javax.swing.JFrame {

    private ListaEmpleados ListaEmpleados = new ListaEmpleados();
    private LinkedList Materiales = new LinkedList();
    private LinkedList Productos = new LinkedList();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar_empleado = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_empleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_id_empleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sp_edad_empleado = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion_empleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sp_salario_empleado = new javax.swing.JSpinner();
        rb_trabaja_agregar = new javax.swing.JRadioButton();
        btn_agregar_empleado = new javax.swing.JButton();
        jd_eliminar_empleado = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        cb_eliminar_empleado = new javax.swing.JComboBox();
        btn_eliminar_empleado = new javax.swing.JButton();
        jd_modificar_empleado = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre_empleado_modificar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_id_empleado_modificar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sp_edad_empleado_modificar = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txt_direccion_empleado_modificar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sp_salario_empleado_modificar = new javax.swing.JSpinner();
        rb_trabaja_modificar = new javax.swing.JRadioButton();
        btn_agregar_empleado_modificar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jd_agregar_orden = new javax.swing.JDialog();
        jd_eliminar_orden = new javax.swing.JDialog();
        jd_agregar_materiales = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        materialAgregarNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        materialAgregarDescripcion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        materialAgregarMarca = new javax.swing.JTextField();
        materialAgregarBotonGuardar = new javax.swing.JButton();
        jd_modificar_materiales = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        materialModificarNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        materialModificarDescripcion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        materialModificarMarca = new javax.swing.JTextField();
        materialModificarBotonGuardar = new javax.swing.JButton();
        materialModificarSeleccionado = new javax.swing.JComboBox<>();
        jd_eliminar_materiales = new javax.swing.JDialog();
        materialEliminarSeleccionado = new javax.swing.JComboBox<>();
        materialEliminarBotonEliminar = new javax.swing.JButton();
        jd_agregar_productos = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        productoAgregarNombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        productoAgregarDescripcion = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productoAgregarMateriales = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        productoAgregarTiempoEnsamblado = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jd_modificar_producto = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        productoModificarDescripcion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productoModificarMateriales = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        productoModificarTiempoEnsamblado = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        productoModificarSeleccionado = new javax.swing.JComboBox<>();
        productoModificarNombre = new javax.swing.JTextField();
        jd_eliminar_producto = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jLabel1.setText("Agregar Empleados");

        jLabel2.setText("Nombre:");

        jLabel3.setText("ID:");

        jLabel4.setText("Edad:");

        sp_edad_empleado.setModel(new javax.swing.SpinnerNumberModel(18, 18, 70, 1));

        jLabel5.setText("Dirección:");

        jLabel6.setText("Salario:");

        sp_salario_empleado.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1000.0d));

        rb_trabaja_agregar.setText("Actualmente Trabajando en una orden?");
        rb_trabaja_agregar.setEnabled(false);

        btn_agregar_empleado.setText("Agregar Empleado");
        btn_agregar_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar_empleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregar_empleadoLayout = new javax.swing.GroupLayout(jd_agregar_empleado.getContentPane());
        jd_agregar_empleado.getContentPane().setLayout(jd_agregar_empleadoLayout);
        jd_agregar_empleadoLayout.setHorizontalGroup(
            jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_empleadoLayout.createSequentialGroup()
                .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_agregar_empleado)
                    .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_agregar_empleadoLayout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(jLabel1))
                        .addGroup(jd_agregar_empleadoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregar_empleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(sp_salario_empleado))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregar_empleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_direccion_empleado))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregar_empleadoLayout.createSequentialGroup()
                                    .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_nombre_empleado)
                                        .addComponent(txt_id_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(sp_edad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jd_agregar_empleadoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(rb_trabaja_agregar))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jd_agregar_empleadoLayout.setVerticalGroup(
            jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sp_edad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_direccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sp_salario_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_trabaja_agregar)
                .addGap(27, 27, 27)
                .addComponent(btn_agregar_empleado)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel13.setText("Eliminar Empleado");

        btn_eliminar_empleado.setText("Eliminar");

        javax.swing.GroupLayout jd_eliminar_empleadoLayout = new javax.swing.GroupLayout(jd_eliminar_empleado.getContentPane());
        jd_eliminar_empleado.getContentPane().setLayout(jd_eliminar_empleadoLayout);
        jd_eliminar_empleadoLayout.setHorizontalGroup(
            jd_eliminar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_empleadoLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel13)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(jd_eliminar_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_eliminar_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_eliminar_empleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar_empleado)
                .addGap(161, 161, 161))
        );
        jd_eliminar_empleadoLayout.setVerticalGroup(
            jd_eliminar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addComponent(cb_eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btn_eliminar_empleado)
                .addGap(96, 96, 96))
        );

        jLabel7.setText("Nombre:");

        jLabel8.setText("ID:");

        jLabel9.setText("Edad:");

        sp_edad_empleado_modificar.setModel(new javax.swing.SpinnerNumberModel(18, 18, 70, 1));

        jLabel10.setText("Dirección:");

        jLabel11.setText("Salario:");

        sp_salario_empleado_modificar.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1000.0d));

        rb_trabaja_modificar.setText("Actualmente Trabajando en una orden?");
        rb_trabaja_modificar.setEnabled(false);

        btn_agregar_empleado_modificar.setText("Modificar Empleado");

        jLabel12.setText("Modificar Empleados");

        javax.swing.GroupLayout jd_modificar_empleadoLayout = new javax.swing.GroupLayout(jd_modificar_empleado.getContentPane());
        jd_modificar_empleado.getContentPane().setLayout(jd_modificar_empleadoLayout);
        jd_modificar_empleadoLayout.setHorizontalGroup(
            jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_empleadoLayout.createSequentialGroup()
                .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_agregar_empleado_modificar)
                    .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_modificar_empleadoLayout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(jLabel12))
                        .addGroup(jd_modificar_empleadoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modificar_empleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(sp_salario_empleado_modificar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modificar_empleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_direccion_empleado_modificar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modificar_empleadoLayout.createSequentialGroup()
                                    .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_nombre_empleado_modificar)
                                        .addComponent(txt_id_empleado_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(sp_edad_empleado_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jd_modificar_empleadoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(rb_trabaja_modificar))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jd_modificar_empleadoLayout.setVerticalGroup(
            jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nombre_empleado_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_id_empleado_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_edad_empleado_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_direccion_empleado_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_modificar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_salario_empleado_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_trabaja_modificar)
                .addGap(27, 27, 27)
                .addComponent(btn_agregar_empleado_modificar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregar_ordenLayout = new javax.swing.GroupLayout(jd_agregar_orden.getContentPane());
        jd_agregar_orden.getContentPane().setLayout(jd_agregar_ordenLayout);
        jd_agregar_ordenLayout.setHorizontalGroup(
            jd_agregar_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_agregar_ordenLayout.setVerticalGroup(
            jd_agregar_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_eliminar_ordenLayout = new javax.swing.GroupLayout(jd_eliminar_orden.getContentPane());
        jd_eliminar_orden.getContentPane().setLayout(jd_eliminar_ordenLayout);
        jd_eliminar_ordenLayout.setHorizontalGroup(
            jd_eliminar_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_eliminar_ordenLayout.setVerticalGroup(
            jd_eliminar_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jd_agregar_materiales.setTitle("Agregar Material");

        jLabel14.setText("Nombre");

        jLabel15.setText("Descripción");

        jLabel16.setText("Marca");

        materialAgregarBotonGuardar.setText("Guardar");
        materialAgregarBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialAgregarBotonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregar_materialesLayout = new javax.swing.GroupLayout(jd_agregar_materiales.getContentPane());
        jd_agregar_materiales.getContentPane().setLayout(jd_agregar_materialesLayout);
        jd_agregar_materialesLayout.setHorizontalGroup(
            jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_materialesLayout.createSequentialGroup()
                .addGroup(jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregar_materialesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(materialAgregarDescripcion)
                            .addComponent(materialAgregarMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(materialAgregarNombre)))
                    .addGroup(jd_agregar_materialesLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(materialAgregarBotonGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregar_materialesLayout.setVerticalGroup(
            jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_materialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(materialAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(materialAgregarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(materialAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(materialAgregarBotonGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_modificar_materiales.setTitle("Modificar Material");

        jLabel17.setText("Nombre");

        jLabel18.setText("Descripción");

        jLabel19.setText("Marca");

        materialModificarBotonGuardar.setText("Guardar");
        materialModificarBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialModificarBotonGuardarActionPerformed(evt);
            }
        });

        materialModificarSeleccionado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                materialModificarSeleccionadoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_modificar_materialesLayout = new javax.swing.GroupLayout(jd_modificar_materiales.getContentPane());
        jd_modificar_materiales.getContentPane().setLayout(jd_modificar_materialesLayout);
        jd_modificar_materialesLayout.setHorizontalGroup(
            jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_materialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialModificarSeleccionado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jd_modificar_materialesLayout.createSequentialGroup()
                        .addGroup(jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(materialModificarDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(materialModificarNombre)
                            .addComponent(materialModificarMarca))))
                .addContainerGap())
            .addGroup(jd_modificar_materialesLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(materialModificarBotonGuardar)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jd_modificar_materialesLayout.setVerticalGroup(
            jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_materialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(materialModificarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(materialModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(materialModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(materialModificarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(materialModificarBotonGuardar)
                .addContainerGap())
        );

        materialEliminarBotonEliminar.setText("Eliminar");
        materialEliminarBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialEliminarBotonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminar_materialesLayout = new javax.swing.GroupLayout(jd_eliminar_materiales.getContentPane());
        jd_eliminar_materiales.getContentPane().setLayout(jd_eliminar_materialesLayout);
        jd_eliminar_materialesLayout.setHorizontalGroup(
            jd_eliminar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_materialesLayout.createSequentialGroup()
                .addGroup(jd_eliminar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminar_materialesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(materialEliminarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_eliminar_materialesLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(materialEliminarBotonEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_eliminar_materialesLayout.setVerticalGroup(
            jd_eliminar_materialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_materialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(materialEliminarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(materialEliminarBotonEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Nombre");

        jLabel21.setText("Descripción");

        jLabel22.setText("Tiempo Ensamblado (s)");

        productoAgregarMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", "Material"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productoAgregarMateriales.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(productoAgregarMateriales);

        jLabel23.setText("Materiales");

        productoAgregarTiempoEnsamblado.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 5));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregar_productosLayout = new javax.swing.GroupLayout(jd_agregar_productos.getContentPane());
        jd_agregar_productos.getContentPane().setLayout(jd_agregar_productosLayout);
        jd_agregar_productosLayout.setHorizontalGroup(
            jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregar_productosLayout.createSequentialGroup()
                        .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productoAgregarDescripcion)
                            .addComponent(productoAgregarNombre)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(productoAgregarTiempoEnsamblado)))
                    .addGroup(jd_agregar_productosLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_agregar_productosLayout.setVerticalGroup(
            jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(productoAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(productoAgregarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(productoAgregarTiempoEnsamblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("Descripción");

        jLabel25.setText("Tiempo Ensamblado (s)");

        productoModificarMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", "Material"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productoModificarMateriales.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(productoModificarMateriales);

        jLabel26.setText("Materiales");

        productoModificarTiempoEnsamblado.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 5));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel27.setText("Nombre");

        javax.swing.GroupLayout jd_modificar_productoLayout = new javax.swing.GroupLayout(jd_modificar_producto.getContentPane());
        jd_modificar_producto.getContentPane().setLayout(jd_modificar_productoLayout);
        jd_modificar_productoLayout.setHorizontalGroup(
            jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_productoLayout.createSequentialGroup()
                .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_productoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productoModificarDescripcion)
                            .addComponent(productoModificarNombre)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(productoModificarTiempoEnsamblado)))
                    .addGroup(jd_modificar_productoLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_modificar_productoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productoModificarSeleccionado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_modificar_productoLayout.setVerticalGroup(
            jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productoModificarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(productoModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(productoModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(productoModificarTiempoEnsamblado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_eliminar_productoLayout = new javax.swing.GroupLayout(jd_eliminar_producto.getContentPane());
        jd_eliminar_producto.getContentPane().setLayout(jd_eliminar_productoLayout);
        jd_eliminar_productoLayout.setHorizontalGroup(
            jd_eliminar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_eliminar_productoLayout.setVerticalGroup(
            jd_eliminar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trump Tower");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyect_1_estructura_de_datos/maxresdefault.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");

        jMenu1.setText("Materiales");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        jMenuItem4.setText("Agregar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setText("Modificar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Eliminar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleado");

        jMenuItem5.setText("Agregar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem11.setText("Modificar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem7.setText("Eliminar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ordenes");

        jMenuItem6.setText("Agregar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem10.setText("Eliminar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3090, 3090, 3090))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1191, 1191, 1191)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try {
            if (this.ListaEmpleados.getTamano() == 0) {
                JOptionPane.showMessageDialog(this, "Error de Capa 8", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_eliminar_empleado.getModel();
                for (int i = 0; i < ListaEmpleados.getTamano(); i++) {
                    modelo.addElement(ListaEmpleados.get(i));
                }
                cb_eliminar_empleado.setModel(modelo);
                this.jd_eliminar_empleado.setModal(true);
                this.jd_eliminar_empleado.pack();
                this.jd_eliminar_empleado.setVisible(true);
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.jd_agregar_empleado.setModal(true);
        this.jd_agregar_empleado.pack();
        this.jd_agregar_empleado.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        if (this.ListaEmpleados.getTamano() == 0) {
            JOptionPane.showMessageDialog(this, "Error de Capa 8", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.jd_modificar_empleado.setModal(true);
            this.jd_modificar_empleado.pack();
            this.jd_modificar_empleado.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        if (this.Productos.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "Error de Capa 8", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.jd_agregar_orden.setModal(true);
            this.jd_agregar_orden.pack();
            this.jd_agregar_orden.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        if (this.Productos.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "Error de Capa 8", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.jd_eliminar_orden.setModal(true);
            this.jd_eliminar_orden.pack();
            this.jd_eliminar_orden.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.jd_agregar_materiales.setModal(true);
        this.jd_agregar_materiales.pack();
        this.jd_agregar_materiales.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (this.Materiales.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No hay Registros de Materiales", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            this.materialModificarSeleccionado.setModel(new DefaultComboBoxModel());
            for (int i = 0; i < this.Materiales.getSize(); i++) {
                this.materialModificarSeleccionado.addItem(this.Materiales.get(i).toString());
            }
            this.materialModificarNombre.setText(((Material) this.Materiales.first()).getNombre());
            this.materialModificarDescripcion.setText(((Material) this.Materiales.first()).getDescripcion());
            this.materialModificarMarca.setText(((Material) this.Materiales.first()).getMarca());
            this.jd_modificar_materiales.setModal(true);
            this.jd_modificar_materiales.pack();
            this.jd_modificar_materiales.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (this.Materiales.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No hay Registros de Materiales", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            this.materialEliminarSeleccionado.setModel(new DefaultComboBoxModel());
            for (int i = 0; i < this.Materiales.getSize(); i++) {
                this.materialEliminarSeleccionado.addItem(this.Materiales.get(i).toString());
            }
            this.jd_eliminar_materiales.setModal(true);
            this.jd_eliminar_materiales.pack();
            this.jd_eliminar_materiales.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if (this.Materiales.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No hay Registros de Materiales", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel Modelo = (DefaultTableModel) this.productoAgregarMateriales.getModel();
            Modelo.setColumnCount(2);
            Object[] Identifiers = {"", "Materiales"};
            Modelo.setColumnIdentifiers(Identifiers);
            Modelo.removeRow(0);
            Object[] Material = new Object[2];
            Material[0] = false;
            for (int i = 0; i < this.Materiales.getSize(); i++) {
                Material[1] = this.Materiales.get(i);
                Modelo.addRow(Material);
            }
            this.productoAgregarMateriales.setModel(Modelo);
            this.productoAgregarMateriales.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.productoAgregarMateriales.getColumnModel().getColumn(0).setPreferredWidth(20);
            this.productoAgregarMateriales.getColumnModel().getColumn(1).setPreferredWidth(600);
            this.productoAgregarMateriales.getTableHeader().setResizingAllowed(false);
            this.jd_agregar_productos.setModal(true);
            this.jd_agregar_productos.pack();
            this.jd_agregar_productos.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        if (this.Productos.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No hay Registros de Productos", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            this.productoModificarNombre.setText(((Producto) this.Productos.get(0)).getNombre());
            this.productoModificarDescripcion.setText(((Producto) this.Productos.get(0)).getNombre());
            this.productoModificarTiempoEnsamblado.setValue(((Producto) this.Productos.get(0)).getTiempoEnsamblado());
            DefaultTableModel Modelo = (DefaultTableModel) this.productoAgregarMateriales.getModel();
            Modelo.setColumnCount(2);
            Object[] Identifiers = {"", "Materiales"};
            Modelo.setColumnIdentifiers(Identifiers);
            Modelo.removeRow(0);
            Object[] Material = new Object[2];
            Material[0] = false;
            for (int i = 0; i < this.Materiales.getSize(); i++) {
                Material[1] = this.Materiales.get(i);
                Material[0] = false;
                for (int j = 0; j < ((Producto) this.Productos.get(i)).getMateriales().getSize(); j++) {
                    if (((Producto) this.Productos.get(i)).getMateriales().get(j).equals(Material[1])) {
                        Material[0] = true;
                    }
                }
                Modelo.addRow(Material);
            }
            this.productoModificarMateriales.setModel(Modelo);
            this.productoModificarMateriales.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.productoModificarMateriales.getColumnModel().getColumn(0).setPreferredWidth(20);
            this.productoModificarMateriales.getColumnModel().getColumn(1).setPreferredWidth(600);
            this.productoModificarMateriales.getTableHeader().setResizingAllowed(false);
            this.productoModificarMateriales.getTableHeader().setReorderingAllowed(false);
            this.jd_modificar_producto.setModal(true);
            this.jd_modificar_producto.pack();
            this.jd_modificar_producto.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        if (this.Productos.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No hay Registros de Materiales", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            this.jd_eliminar_producto.setModal(true);
            this.jd_eliminar_producto.pack();
            this.jd_eliminar_producto.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btn_agregar_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_empleadoMouseClicked
        // TODO add your handling code here:
        String nombre = this.txt_nombre_empleado.getText();
        int id = Integer.parseInt(this.txt_id_empleado.getText());
        int edad = (int) this.sp_edad_empleado.getValue();
        String direccion = this.txt_direccion_empleado.getText();
        double salario = (double) this.sp_salario_empleado.getValue();
        boolean trabaja = false;
        this.ListaEmpleados.insert(new Empleado(nombre, id, edad, direccion, salario, trabaja));
        this.ListaEmpleados.Print_Lista();
    }//GEN-LAST:event_btn_agregar_empleadoMouseClicked

    private void materialAgregarBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialAgregarBotonGuardarActionPerformed
        if (this.materialAgregarNombre.getText().equals("") || this.materialAgregarDescripcion.getText().equals("") || this.materialAgregarMarca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Existe un Campo Vacio", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else if (this.Materiales.getSize() == 0) {
            Materiales.add(new Material(this.materialAgregarNombre.getText(), this.materialAgregarDescripcion.getText(), this.materialAgregarMarca.getText(), ""));
            this.materialAgregarNombre.setText("");
            this.materialAgregarDescripcion.setText("");
            this.materialAgregarMarca.setText("");
            this.jd_agregar_materiales.setModal(false);
            this.jd_agregar_materiales.setVisible(false);
        } else {
            Materiales.add(new Material(this.materialAgregarNombre.getText(), this.materialAgregarDescripcion.getText(), this.materialAgregarMarca.getText(), ((Material) this.Materiales.get(this.Materiales.getSize() - 1)).getSerie()));
            this.materialAgregarNombre.setText("");
            this.materialAgregarDescripcion.setText("");
            this.materialAgregarMarca.setText("");
            this.jd_agregar_materiales.setModal(false);
            this.jd_agregar_materiales.setVisible(false);
        }
    }//GEN-LAST:event_materialAgregarBotonGuardarActionPerformed

    private void materialModificarBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialModificarBotonGuardarActionPerformed
        if (this.materialModificarNombre.getText().equals("") || this.materialModificarDescripcion.getText().equals("") || this.materialModificarMarca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Existe un Campo Vacio", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            ((Material) this.Materiales.get(this.materialModificarSeleccionado.getSelectedIndex())).setNombre(this.materialModificarNombre.getText());
            ((Material) this.Materiales.get(this.materialModificarSeleccionado.getSelectedIndex())).setDescripcion(this.materialModificarDescripcion.getText());
            ((Material) this.Materiales.get(this.materialModificarSeleccionado.getSelectedIndex())).setMarca(this.materialModificarMarca.getText());
            this.jd_modificar_materiales.setModal(false);
            this.jd_modificar_materiales.setVisible(false);
        }
    }//GEN-LAST:event_materialModificarBotonGuardarActionPerformed

    private void materialEliminarBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialEliminarBotonEliminarActionPerformed
        this.Materiales.remove(this.materialEliminarSeleccionado.getSelectedIndex());
        this.jd_eliminar_materiales.setModal(false);
        this.jd_eliminar_materiales.setVisible(false);
    }//GEN-LAST:event_materialEliminarBotonEliminarActionPerformed

    private void materialModificarSeleccionadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_materialModificarSeleccionadoItemStateChanged
        this.materialModificarNombre.setText(((Material) this.Materiales.get(this.materialModificarSeleccionado.getSelectedIndex())).getNombre());
        this.materialModificarDescripcion.setText(((Material) this.Materiales.get(this.materialModificarSeleccionado.getSelectedIndex())).getDescripcion());
        this.materialModificarMarca.setText(((Material) this.Materiales.get(this.materialModificarSeleccionado.getSelectedIndex())).getMarca());
    }//GEN-LAST:event_materialModificarSeleccionadoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.productoAgregarNombre.getText().equals("") || this.productoAgregarDescripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Existe un Campo Vacio", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean materialEscogido = false;
            for (int i = 0; i < this.productoAgregarMateriales.getRowCount(); i++) {
                if ((boolean) this.productoAgregarMateriales.getValueAt(i, 0)) {
                    materialEscogido = true;
                    break;
                }
            }
            if (materialEscogido) {
                LinkedList Materiales = new LinkedList();
                for (int i = 0; i < this.productoAgregarMateriales.getRowCount(); i++) {
                    if ((boolean) this.productoAgregarMateriales.getValueAt(i, 0)) {
                        Materiales.add(this.productoAgregarMateriales.getValueAt(i, 1));
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No Eligio Materiales para el Producto", "Error de Capa 8", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_empleado;
    private javax.swing.JButton btn_agregar_empleado_modificar;
    private javax.swing.JButton btn_eliminar_empleado;
    private javax.swing.JComboBox cb_eliminar_empleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
<<<<<<< HEAD
=======
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
>>>>>>> 3a2e72bdd0a5bc6821f410fc1490509f81351488
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_agregar_empleado;
    private javax.swing.JDialog jd_agregar_materiales;
    private javax.swing.JDialog jd_agregar_orden;
    private javax.swing.JDialog jd_agregar_productos;
    private javax.swing.JDialog jd_eliminar_empleado;
    private javax.swing.JDialog jd_eliminar_materiales;
    private javax.swing.JDialog jd_eliminar_orden;
    private javax.swing.JDialog jd_eliminar_producto;
    private javax.swing.JDialog jd_modificar_empleado;
    private javax.swing.JDialog jd_modificar_materiales;
    private javax.swing.JDialog jd_modificar_producto;
    private javax.swing.JButton materialAgregarBotonGuardar;
    private javax.swing.JTextField materialAgregarDescripcion;
    private javax.swing.JTextField materialAgregarMarca;
    private javax.swing.JTextField materialAgregarNombre;
    private javax.swing.JButton materialEliminarBotonEliminar;
    private javax.swing.JComboBox<String> materialEliminarSeleccionado;
    private javax.swing.JButton materialModificarBotonGuardar;
    private javax.swing.JTextField materialModificarDescripcion;
    private javax.swing.JTextField materialModificarMarca;
    private javax.swing.JTextField materialModificarNombre;
    private javax.swing.JComboBox<String> materialModificarSeleccionado;
    private javax.swing.JTextField productoAgregarDescripcion;
    private javax.swing.JTable productoAgregarMateriales;
    private javax.swing.JTextField productoAgregarNombre;
    private javax.swing.JSpinner productoAgregarTiempoEnsamblado;
    private javax.swing.JTextField productoModificarDescripcion;
    private javax.swing.JTable productoModificarMateriales;
    private javax.swing.JTextField productoModificarNombre;
    private javax.swing.JComboBox<String> productoModificarSeleccionado;
    private javax.swing.JSpinner productoModificarTiempoEnsamblado;
    private javax.swing.JRadioButton rb_trabaja_agregar;
    private javax.swing.JRadioButton rb_trabaja_modificar;
    private javax.swing.JSpinner sp_edad_empleado;
    private javax.swing.JSpinner sp_edad_empleado_modificar;
    private javax.swing.JSpinner sp_salario_empleado;
    private javax.swing.JSpinner sp_salario_empleado_modificar;
    private javax.swing.JTextField txt_direccion_empleado;
    private javax.swing.JTextField txt_direccion_empleado_modificar;
    private javax.swing.JTextField txt_id_empleado;
    private javax.swing.JTextField txt_id_empleado_modificar;
    private javax.swing.JTextField txt_nombre_empleado;
    private javax.swing.JTextField txt_nombre_empleado_modificar;
    // End of variables declaration//GEN-END:variables
}
